version: '3.7'

services:
  vibe:
    container_name: vibe
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 5000:5000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: python3 app.py